# Generated by Django 6.0.7 on 2026-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Psychologist', 'Psychologist'), ('Paediatrician', 'Paediatrician')], max_length=255),
        ),
    ]
