# Generated by Django 6.0.7 on 2026-07-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_doc_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Psychologist', 'Psychologist'), ('Paediatrician', 'Paediatrician')], max_length=50),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
