# Generated by Django 5.2.7 on 2026-09-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctors_doc_spec_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Psychologist', 'Psychologist'), ('Paediatrician', 'Paediatrician')], max_length=255),
        ),
    ]
